sudo: true
language: go

branches:
  only:
    - master
    - /v*/

jobs:
  include:
    - stage: Build desktop MAC
      if: branch =~ /v*/
      os: osx
      language: node_js
      node_js:
        - "9"
      script:
        - cd desktop
        - npm install
        - yarn dist
    - stage: Build desktop Linux
      if: branch =~ /v*/
      os: linux
      dist: ubuntu
      language: node_js
      node_js:
        - "9"
      script:
        - cd desktop
        - npm install
        - yarn dist
    - stage: Deploy back
      if: branch = master
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - cd back
        - docker build -t goncharovnikita/wallpaperize:back --rm .
        - docker push goncharovnikita/wallpaperize:back
    - stage: Deploy app
      if: branch = master
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - cd app
        - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        - dep ensure
        - make deploy
    - stage: Deploy web
      if: branch = master
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - cd web
        - docker build -t goncharovnikita/wallpaperize:web --rm .
        - docker push goncharovnikita/wallpaperize:web