sudo: true
language: go

before_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

branches:
  only:
    - master

jobs:
  include:
    - stage: Build desktop MAC
      os: osx
      script:
        - cd desktop
        - npm install
        - yarn dist