sudo: true
language: go

branches:
  only:
    - master

jobs:
  include:
    - stage: Build desktop MAC
      os: osx
      language: node_js
      node_js:
        - "9"
      script:
        - cd desktop
        - npm install
        - yarn dist
    - stage: Build desktop Linux
      os: linux
      dist: ubuntu
      language: node_js
      node_js:
        - "9"
      script:
        - cd desktop
        - npm install
        - yarn dist