sudo: true
language: go

before_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

branches:
  only:
    - master

jobs:
  include:
    - deploy_back:
      script:
        - cd back
        - docker build -t goncharovnikita/wallpaperize:back --rm .
        - docker push goncharovnikita/wallpaperize:back
    - deploy_app:
      script:
        - cd app
        # - curl https://glide.sh/get | sh
        # - glide install
        - make deploy
    - deploy_web:
      script:
        - cd web
        - docker build -t goncharovnikita/wallpaperize:web --rm .
        - docker push goncharovnikita/wallpaperize:web