sudo: true
language: go

branches:
  only:
    - master

jobs:
  include:
    - stage: Build desktop MAC
      if: tag IS present
      os: osx
      language: node_js
      node_js:
        - "9"
      script:
        - cd desktop
        - npm install
        - yarn dist