sudo: true
language: go

branches:
  only:
    - master

jobs:
  include:
    - stage: Build desktop MAC
      os: osx
      language: node_js
      script:
        - cd desktop
        - npm install
        - yarn dist