sudo: true
dist: trusty

jobs:
  include:
    deploy_back:
      script:
        - cd back
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker build -t goncharovnikita/wallpaperize:back --rm .
        - docker push goncharovnikita/wallpaperize:back