sudo: true
dist: trusty
language: go

jobs:
  include:
    - deploy_back:
      script:
        - cd back
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker build -t goncharovnikita/wallpaperize:back --rm .
        - docker push goncharovnikita/wallpaperize:back
    - deploy_app:
      script:
        - cd app
        - curl https://glide.sh/get | sh
        - glide install
        - make deploy